### ISSUE TITLE
Jpg file (Mac OS 10.10.3) doesn't download correctly

### ISSUE THREAD

**Issue by martimij** [oncogenetics/LocusExplorer#78] opened 2015-10-21 14:29 UTC
Linked to issue #79

**Comment by zx8754** [comment] 2015-10-21 14:35
@martimij Do you mean there is no jpeg output file or the jpeg output file is wrong?

**Comment by martimij** [comment] 2015-10-21 14:48
The output file is wrong, please see issue #79

**Comment by zx8754** [comment] 2015-10-21 16:19
Duplicate of #79

**Closed by zx8754** 2015-10-21 16:19 UTC
Labels: bug, duplicate
